name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build_and_test_backend:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 })' -u root -p example --authenticationDatabase admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PORT: 3003
      SECRET: IDDQD
      TEST_MONGODB_URI: mongodb://root:example@localhost:27017/the_database_test?authSource=admin

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install deps
        working-directory: ./backend
        run: |
          npm ci

      - name: Check style
        working-directory: ./backend
        run: npm run lint

      - name: Run unit tests
        working-directory: ./backend
        run: npm test

  build_and_test_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install deps
        working-directory: ./frontend
        run: |
          npm ci

      - name: Check style
        working-directory: ./frontend
        run: npm run lint

      - name: Run unit tests
        working-directory: ./frontend
        run: npm test

  deploy:
    needs: [build_and_test_backend, build_and_test_frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and tag it
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notification:
    needs: deploy
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on success
        if: ${{ needs.deploy.result == 'success' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.deploy.result }}
          title: "Deployment completed successfully"

      - name: Send notification on failure
        if: ${{ needs.deploy.result == 'failure' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.deploy.result }}
          title: "Deployment failed"
          description: "The commit: ${{ github.sha }}"
