name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build_and_test_backend:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 })' -u root -p example --authenticationDatabase admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PORT: 3003
      SECRET: IDDQD
      TEST_MONGODB_URI: mongodb://root:example@localhost:27017/the_database_test?authSource=admin

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install deps
        working-directory: ./backend
        run: |
          npm ci

      - name: Check style
        working-directory: ./backend
        run: npm run lint

      - name: Run unit tests
        working-directory: ./backend
        run: npm test
